instagram/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from . import views
from post import views as post_views
from member import views as member_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^post/', include('post.urls', namespace='post')),
    url(r'^member/', include('member.urls', namespace='member')),
    url(r'^$', views.redirect_post_list)
]
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

instagram/post/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^create/$', views.post_create, name='post_create'),
    url(r'^(?P<post_pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<post_pk>\d+)/delete', views.post_delete, name='post_delete'),
    url(r'^(?P<post_pk>\d+)/like-toggle/$', views.post_like_toggle, name='post_like_toggle'),


    url(r'^(?P<comment_pk>\d+)/comment/delete', views.comment_delete, name='comment_delete'),
    url(r'^(?P<post_pk>\d+)/comment/create/$', views.comment_create, name='comment_create'),
]

instagram/post/models.py
from django.conf import settings
from django.db import models


class Postmanager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().exclude(author=None)


class Post(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )
    photo = models.ImageField(
        upload_to='post'
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )

    objects = Postmanager()

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f'Post (PK: {self.pk}'


class PostComment(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        blank=True,
        null=True
    )
    post = models.ForeignKey(
        Post,
        related_name='comments'
    )
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta():
        ordering = ['created_at']

instagram/post/forms.py
from django import forms

from .models import Post, PostComment

__all__ = (
    'PostForm',
    'CommentForm'
)


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'photo',
        )

    def save(self, commit=True, *args, **kwargs):
        if not self.instance.pk and commit:
            author = kwargs.pop('author', None)
            if not author:
                raise ValueError('Author field is required')
            self.instance.author = author
        return super().save(*args, **kwargs)


class CommentForm(forms.ModelForm):
    class Meta:
        model = PostComment
        fields = (
            'content',
        )
        widget = {
            'content': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            )
        }

instagram/post/urls/views.py
from django.conf.urls import url

from .. import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^create/$', views.post_create, name='post_create'),
    url(r'^(?P<post_pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<post_pk>\d+)/delete', views.post_delete, name='post_delete'),
    url(r'^(?P<post_pk>\d+)/like-toggle/$', views.post_like_toggle, name='post_like_toggle'),


    url(r'^(?P<comment_pk>\d+)/comment/delete', views.comment_delete, name='comment_delete'),
    url(r'^(?P<post_pk>\d+)/comment/create/$', views.comment_create, name='comment_create'),
]

instagram/post/views.py
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

from member.decorators import login_required
from post.forms import PostForm, CommentForm
from post.models import Post, PostComment



def post_list(request):
    posts = Post.objects.all()
    comment_form = CommentForm()
    context = {
        'posts': posts,
        'comment_form': comment_form
    }
    return render(request, 'post/post_list.html', context)


def post_create(request):
    if not request.user.is_authenticated():
        return redirect('member:login')
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('post:post_list')
    else:
        form = PostForm()  # GET요청의 경우, 빈 PostForm인스턴스를 생성해서 템플릿에 전달
    context = {
        'form': form,
    }
    return render(request, 'post/post_create.html', context)


def post_detail(request, post_pk):
    # post = Post.objects.get(pk=post_pk)
    # 겟을 했을 때 pk번호가 유효하지 않으면
    # 500번대 서버 에러메시지를 보여주게 되는데
    # 404 메시지를 보여주는게 좀더 정확하기 때문에 아래의 코드로 대체힌다.
    post = get_object_or_404(Post, pk=post_pk)
    comment_form = CommentForm()
    context = {
        'post': post,
        'comment_form': comment_form,
    }
    return render(request, 'post/post_detail.html', context)


def post_delete(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    if request.method == 'POST':
        if request.user == post.author:
            post.delete()
            return redirect('post:post_list')
        else:
            raise PermissionDenied
    return HttpResponse('로그인 후 이용하세요')

@login_required
def post_like_toggle(request, post_pk):
    next_path = request.GET.get('next')
    post = get_object_or_404(Post, pk=post_pk)
    user = request.user
    filtered_like_posts = user.like_posts.filter(pk=post.pk)

    if filtered_like_posts.exists():
        user.like_posts.remove(post)
    else:
        user.like_posts.add(post)

    if next_path:
        return redirect(next_path)
    return redirect('post:post_detail', post_pk=post_pk)

@login_required
def comment_create(request, post_pk):
    if not request.user.is_authenticated():
        return redirect('member:login')
    post = get_object_or_404(Post, pk=post_pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            next = request.GET.get('next', '').strip()
            # post_list페이지 에서 댓글을 달더라도 post_create페이지로
            # 이동 하는 것이 아니라 post_list에서 바로 작성될 수 있도록 해주기 위해
            # 탬플릿의 form 태그에 get파라미터를 추가하고
            # 아래의 if 문으로 get 파라미터의 키 값인
            # next를 확인하해서 post_list로 리다이렉트 해준다.
            if next:
                return redirect(next)
            return redirect('post:post_detail', post_pk=post_pk)


def comment_delete(request, comment_pk):
    comment = PostComment.objects.get(pk=comment_pk)
    if request.method == 'POST':
        if request.user == comment.author:
            comment.delete()
            return redirect('post:post_list')
    return HttpResponse('로그인이 필요합니다.')

instagram/post/views/comment.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect

from member.decorators import login_required
from post.forms import CommentForm
from post.models import Post, PostComment

__all__ = (
    'comment_create',
    'comment_delete',
)


@login_required
def comment_create(request, post_pk):
    if not request.user.is_authenticated():
        return redirect('member:login')
    post = get_object_or_404(Post, pk=post_pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            next = request.GET.get('next', '').strip()
            # post_list페이지 에서 댓글을 달더라도 post_create페이지로
            # 이동 하는 것이 아니라 post_list에서 바로 작성될 수 있도록 해주기 위해
            # 탬플릿의 form 태그에 get파라미터를 추가하고
            # 아래의 if 문으로 get 파라미터의 키 값인
            # next를 확인하해서 post_list로 리다이렉트 해준다.
            if next:
                return redirect(next)
            return redirect('post:post_detail', post_pk=post_pk)


def comment_delete(request, comment_pk):
    comment = PostComment.objects.get(pk=comment_pk)
    if request.method == 'POST':
        if request.user == comment.author:
            comment.delete()
            return redirect('post:post_list')
    return HttpResponse('로그인이 필요합니다.')

instagram/post/views/post.py
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

from member.decorators import login_required
from post.forms import PostForm, CommentForm
from post.models import Post

__all__ = (
    'post_list',
    'post_create',
    'post_detail',
    'post_delete',
    'post_like_toggle',
)


def post_list(request):
    posts = Post.objects.all()
    comment_form = CommentForm()
    context = {
        'posts': posts,
        'comment_form': comment_form
    }
    return render(request, 'post/post_list.html', context)


def post_create(request):
    if not request.user.is_authenticated():
        return redirect('member:login')
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('post:post_list')
    else:
        form = PostForm()  # GET요청의 경우, 빈 PostForm인스턴스를 생성해서 템플릿에 전달
    context = {
        'form': form,
    }
    return render(request, 'post/post_create.html', context)


def post_detail(request, post_pk):
    # post = Post.objects.get(pk=post_pk)
    # 겟을 했을 때 pk번호가 유효하지 않으면
    # 500번대 서버 에러메시지를 보여주게 되는데
    # 404 메시지를 보여주는게 좀더 정확하기 때문에 아래의 코드로 대체힌다.
    post = get_object_or_404(Post, pk=post_pk)
    comment_form = CommentForm()
    context = {
        'post': post,
        'comment_form': comment_form,
    }
    return render(request, 'post/post_detail.html', context)


def post_delete(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    if request.method == 'POST':
        if request.user == post.author:
            post.delete()
            return redirect('post:post_list')
        else:
            raise PermissionDenied
    return HttpResponse('로그인 후 이용하세요')


@login_required
def post_like_toggle(request, post_pk):
    next_path = request.GET.get('next')
    post = get_object_or_404(Post, pk=post_pk)
    user = request.user
    filtered_like_posts = user.like_posts.filter(pk=post.pk)

    if filtered_like_posts.exists():
        user.like_posts.remove(post)
    else:
        user.like_posts.add(post)

    if next_path:
        return redirect(next_path)
    return redirect('post:post_detail', post_pk=post_pk)

instagram/templates/include/form-horizontal.html
<form action="" method="POST" enctype="multipart/form-data" class="form-horizontal">
    {% csrf_token %}
    {% for field in form %}
        <div class="form-group{% if field.errors %} has-error{% endif %}">
            <label
                    for="{{ field.auto_id }}"
                    class="col-xs-2 control-label">
                {{ field.label }}
            </label>
            <div class="col-xs-10">
                {{ field }}
                {% if field.errors %}
                    {% for error in field.errors %}
                        <span class="help-block">{{ error }}</span>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    {% endfor %}
    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
            <p class="text-danger">{{ error }}</p>
        {% endfor %}
    {% endif %}
    <button class="btn btn-primary btn-block">{{ submit_text }}</button>
</form>

instagram/templates/include/post.html
<div id="post-{{ post.pk }}" class="panel panel-default post">
    <div class="panel-heading">{{ post.author }}</div>
    <div>
        {% if post.author == user %}
            <form action="{% url 'post:post_delete' post_pk=post.pk %}" method="POST">
                {% csrf_token %}
                <button>포스트 삭제</button>
            </form>
        {% endif %}
    </div>
    <div class="panel-body">
        <a href="{% url 'post:post_detail' post_pk=post.pk %}">
            <img src="{{ post.photo.url }}" class="img-post">
        </a>
        <div class="body-content">
            <div class="btn-container">
                <form action="{% url 'post:post_like_toggle' post_pk=post.pk %}?next=
						{% if post_type == 'list' %}
							{% url 'post:post_list' %}#post-{{ post.pk }}
						{% elif post_type == 'detail' %}
							{% url 'post:post_detail' post_pk=post.pk %}
						{% endif %}" method="POST">
					{% csrf_token %}
					<button class="btn btn-default border-none" aria-label="Like button">
					  <span
						  class="glyphicon
						    {% if post in user.like_posts.all %}
						      glyphicon-heart
								{% else %}
									glyphicon-heart-empty
								{% endif %}"
						  aria-hidden="true"></span>
					</button>
				</form>
            </div>
            <ul id="post-comments-{{ post.pk }}">
                {% for comment in post.comments.all %}
                    <li>{{ comment.content }}</li>
                    <form action="{% url 'post:comment_delete' comment_pk=comment.pk %}" method="post">
                        {% csrf_token %}
                        <button>리플삭제</button>
                    </form>
                {% endfor %}
            </ul>
            <form action="{% url 'post:comment_create' post_pk=post.pk %}?next={% if post_type == 'list' %}/post/#post-comments-{{ post.pk }}{% elif post_type == 'detail' %}{% url 'post:post_detail' post_pk=post.pk %}{% endif %}"
                  method="POST">
                {% csrf_token %}
                {{ comment_form }}
                <button class="btn btn-primary btn-block">댓글달기</button>
            </form>
        </div>
    </div>
</div>