instagram/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from . import views
from post import views as post_views
from member import views as member_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^post/', include('post.urls', namespace='post')),
    url(r'^member/', include('member.urls', namespace='member')),
    url(r'^$', views.redirect_post_list)
]
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

instagram/post/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^create/$', views.post_create, name='post_create'),
    url(r'^(?P<post_pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<post_pk>\d+)/delete', views.post_delete, name='post_delete'),
    url(r'^(?P<post_pk>\d+)/like-toggle/$', views.post_like_toggle, name='post_like_toggle'),


    url(r'^(?P<comment_pk>\d+)/comment/delete', views.comment_delete, name='comment_delete'),
    url(r'^(?P<post_pk>\d+)/comment/create/$', views.comment_create, name='comment_create'),
]

instagram/member/urls/views.py
from django.conf.urls import url

from .. import views

urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^facebook-login/$', views.facebook_login, name='facebook_login'),
    url(r'^front-facebook-login/$',
        views.FrontFacebookLogin.as_view(),
        name='front-facebook-login'),
]

instagram/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
	<meta charset="UTF-8">
	<meta name="viewport"
	      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Instagram</title>
	<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'css/post.css' %}">
</head>
<body>
		<div>
			<nav class="navbar navbar-default">
				<div class="col-lg-6 col-lg-offset-3
				col-md-8 col-md-offset-2
				col-sm-10 col-sm-offset-1
				col-xs-12">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-nav">
			        <span class="sr-only">Toggle navigation</span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			      </button>
			      <a class="navbar-brand" href="{% url 'post:post_list' %}">Instagram</a>
					</div>
					<div class="collapse navbar-collapse" id="top-nav">
						<ul class="nav navbar-nav navbar-right">
                            <li><a href="">{{ user.username }}</a></li>
							{% if user.is_authenticated %}
							<li><a href="{% url 'post:post_create' %}">+ Add Post</a></li>
							<li><a href="{% url 'member:logout' %}">Logout</a></li>
							{% else %}
							<li><a href="{% url 'member:login' %}">Login</a></li>
							<li><a href="{% url 'member:signup' %}">Signup</a></li>
							{% endif %}
						</ul>
					</div>
				</div>
			</nav>
			<div class="col-lg-6 col-lg-offset-3
				col-md-8 col-md-offset-2
				col-sm-10 col-sm-offset-1
				col-xs-12">
				{% block content %}
				{% endblock %}
			</div>
		</div>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
</body>


</html>